### ISSUE TITLE
Cannot create cluster: Timeout waiting for ssh key

### ISSUE THREAD

**Issue by re-thc** [montel-ig/ui-driver-upcloud#2]
Hi, using latest Rancher and installed the Upcloud driver.

Tried to create a cluster but get the following error:

`Error with pre-create check: "Authentication failed using the given username and password. (AUTHENTICATION_FAILED)"; Timeout waiting for ssh key`

What is the requirement for ssh key? This wasn't mentioned in the documentation. Thanks.

**Comment by a-rmz** [comment]
Hey @hc-codersatlas! Thanks for reaching out.

This is caused because the user/password combination you provided aren't valid and the [docker-machine driver](https://github.com/montel-ig/docker-machine-driver-upcloud/) can't create the required instances.

We're waiting for response from UpCloud to fix some of the authentication bugs, but we know that it can be kind of a hassle right now. 

Also, thanks for submitting and we'll document in case anyone else bumps into this!
